apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: demo-app-prod

commonLabels:
  environment: production

patches:
- path: patches/deployment-patch.yaml

configMapGenerator:
- name: demo-app-config
  behavior: merge
  literals:
  - NODE_ENV=production
